services:
  ai_engine:
    image: registry.pintarai.com/pintarai/mardi:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: 8g
    # ulimits:
    #   memlock: -1
    #   stack: 67108864
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
      - "8888:8888"
    networks:
      - ai_network
    working_dir: ${DOCKER_ROOT}
    volumes:
      - ${PWD}/${NOTEBOOK_DIR}:${DOCKER_ROOT}/${NOTEBOOK_DIR}
      - ${PWD}/${IMAGES_DIR}:${DOCKER_ROOT}/${IMAGES_DIR}
      - ${PWD}/${SERVER_DIR}:${DOCKER_ROOT}/${SERVER_DIR}
    restart: always
    command: ["sh", "-c", "./start.sh"]

  inference_worker:
    image: registry.pintarai.com/pintarai/mardi:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: 8g
    # ulimits:
    #   memlock: -1
    #   stack: 67108864
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    depends_on:
      - rabbitmq
    networks:
      - ai_network
    working_dir: ${DOCKER_ROOT}
    volumes:
      - ${PWD}/${NOTEBOOK_DIR}:${DOCKER_ROOT}/${NOTEBOOK_DIR}
      - ${PWD}/${IMAGES_DIR}:${DOCKER_ROOT}/${IMAGES_DIR}
      - ${PWD}/${SERVER_DIR}:${DOCKER_ROOT}/${SERVER_DIR}
    restart: always
    command: ["sh", "-c", "python3 server/worker.py"]

  rabbitmq:
    image: rabbitmq:3.13-management
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    hostname: rabbitmq
    networks:
      - ai_network
    environment:
      - RABBITMQ_DEFAULT_USER=mardi
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ${PWD}/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always

networks:
  ai_network:
    name: ai_network
    driver: bridge
